[package]
name = "unsend"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["alloc"]
alloc = []

[dev-dependencies]
futures-lite = "1.13.0"

[dependencies]
async-task = { version = "4.4.0", default-features = false }
