[package]
name = "smol-hello"
version = "0.1.0"
edition = "2018"
authors = ["John Nunley <jtnunley01@gmail.com>"]
license = "LGPL-3.0-or-later OR MPL-2.0"
repository = "https://github.com/notgull/unsend"

[dependencies]
httparse = "1.8.0"
smol = "1.3.0"
